#!/usr/bin/env node
// Kusik icon generator: an SVG folder → typed TSX + a preview page.
//
//   pnpm --filter web icons          — build every pack
//   node scripts/build-icons.mjs icon — one pack only
//
// The SVG files are the source of truth; *.generated.tsx is never edited by hand.
// Copied from design/scripts/build-icons.mjs; only the PACKS paths and the output style differ.
// No dependencies: Node 18+.

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))

const PACKS = {
	icon: {
		svgDir: '../src/shared/ui/icon/svg',
		outFile: '../src/shared/ui/icon/icon.generated.tsx',
		previewFile: '../src/shared/ui/icon/icon.preview.html',
		constName: 'ICON_PATHS',
		namesConst: 'ICON_NAMES',
		typeName: 'IconName',
		viewBox: '0 0 24 24',
		// UI icons are single-colour: currentColor only (or var(...) for cut-outs)
		isMonochrome: true,
	},
	food: {
		svgDir: '../src/shared/ui/food-icon/svg',
		outFile: '../src/shared/ui/food-icon/food-icons.generated.tsx',
		previewFile: '../src/shared/ui/food-icon/food-icons.preview.html',
		constName: 'FOOD_ICON_PATHS',
		namesConst: 'FOOD_ICON_NAMES',
		typeName: 'FoodIconName',
		viewBox: '0 0 32 32',
		isMonochrome: false,
	},
}

const NAME_PATTERN = { icon: /^[a-z0-9]+(-[a-z0-9]+)*$/, food: /^[a-z0-9]+(_[a-z0-9]+)*$/ }

const ATTR_TO_JSX = {
	'stroke-width': 'strokeWidth',
	'stroke-linecap': 'strokeLinecap',
	'stroke-linejoin': 'strokeLinejoin',
	'stroke-dasharray': 'strokeDasharray',
	'stroke-dashoffset': 'strokeDashoffset',
	'stroke-opacity': 'strokeOpacity',
	'fill-opacity': 'fillOpacity',
	'fill-rule': 'fillRule',
	'clip-rule': 'clipRule',
	'stop-color': 'stopColor',
	'text-anchor': 'textAnchor',
	'font-family': 'fontFamily',
	'font-weight': 'fontWeight',
	'font-size': 'fontSize',
	class: 'className',
}

const fail = (file, message) => {
	console.error(`✗ ${file}: ${message}`)
	process.exitCode = 1
}

const readInner = (pack, file) => {
	const source = readFileSync(file, 'utf8').trim()
	const root = source.match(/^<svg\b([^>]*)>([\s\S]*)<\/svg>$/)
	if (!root) return fail(file, 'the file must be a single <svg>…</svg>')
	const [, rootAttrs, inner] = root

	if (!rootAttrs.includes(`viewBox="${pack.viewBox}"`)) {
		return fail(file, `viewBox must be "${pack.viewBox}"`)
	}
	if (/<(script|style|image|foreignObject)\b/i.test(inner)) {
		return fail(file, '<script>, <style>, <image> and <foreignObject> are not allowed')
	}
	if (/\sid="/.test(inner)) {
		return fail(file, 'no ids: they clash when several icons are on one page')
	}
	if (/\son[a-z]+="/i.test(inner)) return fail(file, 'no event handlers')
	if (pack.isMonochrome) {
		const allowed = ['none', 'currentColor']
		for (const [, , color] of inner.matchAll(/(fill|stroke)="([^"]*)"/g)) {
			if (!allowed.includes(color) && !color.startsWith('var(')) {
				return fail(file, `a UI icon can't be ${color} — only currentColor or var(...)`)
			}
		}
	}
	return inner.trim()
}

const toJsx = (inner) =>
	inner
		.replace(/\s([a-z-]+)="/g, (match, attr) =>
			ATTR_TO_JSX[attr] ? ` ${ATTR_TO_JSX[attr]}="` : match,
		)
		.replace(/<(\w+)([^>]*?)\s*\/>/g, '<$1$2 />')
		.replace(/<(\w+)([^>]*)><\/\1>/g, '<$1$2 />')
		.replace(/>\s*</g, '>\n\t\t\t<')

const buildPack = (packName) => {
	const pack = PACKS[packName]
	const svgDir = join(HERE, pack.svgDir)
	if (!existsSync(svgDir)) return fail(svgDir, 'no SVG folder')

	const files = readdirSync(svgDir)
		.filter((fileName) => fileName.endsWith('.svg'))
		.sort()
	const entries = []
	for (const fileName of files) {
		const name = basename(fileName, '.svg')
		const file = join(svgDir, fileName)
		if (!NAME_PATTERN[packName].test(name)) {
			fail(
				file,
				packName === 'icon'
					? 'name it in kebab-case (chevron-left)'
					: 'name it in snake_case, as in the enum (dried_fruit)',
			)
			continue
		}
		const inner = readInner(pack, file)
		if (inner) entries.push({ name, inner })
	}
	if (process.exitCode) return

	const body = entries
		.map(({ name, inner }) => `\t'${name}': (\n\t\t<>\n\t\t\t${toJsx(inner)}\n\t\t</>\n\t),`)
		.join('\n')
	const names = entries.map(({ name }) => `\t'${name}',`).join('\n')
	writeFileSync(
		join(HERE, pack.outFile),
		`// GENERATED by scripts/build-icons.mjs from ${pack.svgDir.replace('../', '')}/*.svg — do not edit.\n` +
			`// To change an icon, edit its SVG and run \`pnpm --filter web icons\`. The file size limit doesn't apply here.\n` +
			`import type { ReactNode } from 'react'\n\n` +
			`export const ${pack.namesConst} = [\n${names}\n] as const\n\n` +
			`export type ${pack.typeName} = (typeof ${pack.namesConst})[number]\n\n` +
			`export const ${pack.constName}: Record<${pack.typeName}, ReactNode> = {\n${body}\n}\n`,
	)

	const strokeAttrs = pack.isMonochrome
		? ' fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"'
		: ''
	const cells = entries
		.map(
			({ name, inner }) =>
				`<figure><svg viewBox="${pack.viewBox}" width="40" height="40"${strokeAttrs}>${inner}</svg><figcaption>${name}</figcaption></figure>`,
		)
		.join('\n')
	writeFileSync(
		join(HERE, pack.previewFile),
		`<!doctype html><meta charset="utf-8"><title>${packName} — ${entries.length}</title>` +
			`<style>body{margin:0;padding:24px;font:600 12px system-ui;background:#FBF6EE;color:#2A2118;display:flex;flex-wrap:wrap;gap:12px}` +
			`figure{margin:0;width:96px;padding:12px 4px;border-radius:16px;background:#fff;display:flex;flex-direction:column;align-items:center;gap:8px}` +
			`figcaption{text-align:center;word-break:break-word;color:#6B5D50}</style>\n${cells}\n`,
	)
	console.log(`✓ ${packName}: ${entries.length} → ${pack.outFile}`)
}

const requested = process.argv.slice(2)
const packNames = requested.length > 0 ? requested : Object.keys(PACKS)
for (const name of packNames) {
	if (PACKS[name]) buildPack(name)
	else fail(name, `unknown pack. Available: ${Object.keys(PACKS).join(', ')}`)
}
