import type { FoodCategory, FoodGroup } from './food.types';

// Група визначає колір плитки під іконкою.
export const FOOD_CATEGORY_GROUP: Record<FoodCategory, FoodGroup> = {
  'eggs': 'grain',
  'porridge': 'grain',
  'cereal': 'grain',
  'pancakes': 'grain',
  'toast': 'grain',
  'bread': 'grain',
  'pastry': 'grain',
  'dumplings': 'grain',
  'pasta': 'grain',
  'pizza': 'grain',
  'soup': 'soup',
  'borscht': 'soup',
  'meat': 'protein',
  'poultry': 'protein',
  'sausage': 'protein',
  'fish': 'protein',
  'seafood': 'protein',
  'potatoes': 'grain',
  'salad': 'plant',
  'vegetables': 'plant',
  'legumes': 'plant',
  'milk': 'dairy',
  'yogurt': 'dairy',
  'cottage_cheese': 'dairy',
  'cheese': 'dairy',
  'fruit': 'plant',
  'banana': 'plant',
  'berries': 'plant',
  'dried_fruit': 'plant',
  'nuts': 'plant',
  'snacks': 'sweet',
  'protein_bar': 'sweet',
  'chocolate': 'sweet',
  'cake': 'sweet',
  'ice_cream': 'sweet',
  'cookies': 'sweet',
  'coffee': 'drink',
  'tea': 'drink',
  'juice': 'drink',
  'soda': 'drink',
  'alcohol': 'drink',
  'protein_shake': 'dairy',
  'fast_food': 'protein',
  'sauce': 'neutral',
  'plate': 'neutral',
};

// Класи з токенів theme.css (--color-food-*).
export const FOOD_GROUP_TILE_CLASS: Record<FoodGroup, string> = {
  grain: 'bg-food-grain',
  soup: 'bg-food-soup',
  protein: 'bg-food-protein',
  plant: 'bg-food-plant',
  dairy: 'bg-food-dairy',
  sweet: 'bg-food-sweet',
  drink: 'bg-food-drink',
  neutral: 'bg-food-neutral',
};

export const foodLabelKey = (category: FoodCategory): string => `food.category.${category}`;
