// GENERATED by scripts/build-icons.mjs from src/shared/ui/icon/svg/*.svg — do not edit.
// To change an icon, edit its SVG and run `pnpm --filter web icons`. The file size limit doesn't apply here.
import type { ReactNode } from 'react'

export const ICON_NAMES = [
	'add-to-home',
	'alert',
	'bell',
	'body',
	'calendar',
	'camera',
	'chat-filled',
	'chat',
	'check',
	'chevron-down',
	'chevron-left',
	'chevron-right',
	'chevron-up',
	'clock',
	'close',
	'desk',
	'dumbbell',
	'edit',
	'export',
	'eye-off',
	'eye',
	'flame',
	'globe',
	'image',
	'info',
	'lock',
	'logout',
	'mail',
	'memory',
	'menu',
	'mic',
	'minus',
	'more',
	'plus',
	'progress-filled',
	'progress',
	'recipes-filled',
	'recipes',
	'retry',
	'scale',
	'search',
	'send',
	'settings',
	'share',
	'sparkle',
	'stop',
	'today',
	'trash',
	'trend-down',
	'trend-flat',
	'walk',
] as const

export type IconName = (typeof ICON_NAMES)[number]

export const ICON_PATHS: Record<IconName, ReactNode> = {
	'add-to-home': (
		<>
			<rect x="4" y="4" width="16" height="16" rx="4" />
			<path d="M12 8v8M8 12h8" />
		</>
	),
	'alert': (
		<>
			<circle cx="12" cy="12" r="9" />
			<path d="M12 7.5v5.5M12 16.5v.5" />
		</>
	),
	'bell': (
		<>
			<path d="M6 16.5V11a6 6 0 0 1 12 0v5.5l1.5 2h-15z" />
			<path d="M10 20.5a2 2 0 0 0 4 0" />
		</>
	),
	'body': (
		<>
			<circle cx="12" cy="6" r="2.5" />
			<path d="M7 21l2-9h6l2 9M9 12l-3-2M15 12l3-2" />
		</>
	),
	'calendar': (
		<>
			<rect x="4" y="5.5" width="16" height="14.5" rx="2.5" />
			<path d="M4 10h16M8.5 3.5v4M15.5 3.5v4" />
		</>
	),
	'camera': (
		<>
			<path d="M4 8.5a2 2 0 0 1 2-2h2l1.5-2h5l1.5 2h2a2 2 0 0 1 2 2V17a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z" />
			<circle cx="12" cy="12.5" r="3.5" />
		</>
	),
	'chat-filled': (
		<>
			<path d="M6 4.5h12a2.5 2.5 0 0 1 2.5 2.5v8a2.5 2.5 0 0 1-2.5 2.5h-7l-4.5 3.5v-3.5H6A2.5 2.5 0 0 1 3.5 15V7A2.5 2.5 0 0 1 6 4.5z" fill="currentColor" />
			<g fill="var(--icon-cutout, #FFFFFF)" stroke="none">
			<circle cx="8.5" cy="11" r="1.2" />
			<circle cx="12" cy="11" r="1.2" />
			<circle cx="15.5" cy="11" r="1.2" />
			</g>
		</>
	),
	'chat': (
		<>
			<path d="M6 4.5h12a2.5 2.5 0 0 1 2.5 2.5v8a2.5 2.5 0 0 1-2.5 2.5h-7l-4.5 3.5v-3.5H6A2.5 2.5 0 0 1 3.5 15V7A2.5 2.5 0 0 1 6 4.5z" />
		</>
	),
	'check': (
		<>
			<path d="M5 12.5l4.5 4.5L19 7.5" />
		</>
	),
	'chevron-down': (
		<>
			<path d="M6 9l6 6 6-6" />
		</>
	),
	'chevron-left': (
		<>
			<path d="M15 6l-6 6 6 6" />
		</>
	),
	'chevron-right': (
		<>
			<path d="M9 6l6 6-6 6" />
		</>
	),
	'chevron-up': (
		<>
			<path d="M6 15l6-6 6 6" />
		</>
	),
	'clock': (
		<>
			<circle cx="12" cy="12" r="8.5" />
			<path d="M12 7.5V12l3 2" />
		</>
	),
	'close': (
		<>
			<path d="M6 6l12 12M18 6L6 18" />
		</>
	),
	'desk': (
		<>
			<rect x="4" y="5" width="16" height="10" rx="1.5" />
			<path d="M9 19h6M12 15v4" />
		</>
	),
	'dumbbell': (
		<>
			<path d="M6 9v6M18 9v6M3 11v2M21 11v2M6 12h12" />
		</>
	),
	'edit': (
		<>
			<path d="M4 20h4L19 9l-4-4L4 16z" />
			<path d="M13.5 6.5l4 4" />
		</>
	),
	'export': (
		<>
			<path d="M12 4v11M8 11l4 4 4-4" />
			<path d="M5 19.5h14" />
		</>
	),
	'eye-off': (
		<>
			<path d="M2.5 12s3.5-6.5 9.5-6.5 9.5 6.5 9.5 6.5-3.5 6.5-9.5 6.5S2.5 12 2.5 12z" />
			<circle cx="12" cy="12" r="3" />
			<path d="M4 4l16 16" />
		</>
	),
	'eye': (
		<>
			<path d="M2.5 12s3.5-6.5 9.5-6.5 9.5 6.5 9.5 6.5-3.5 6.5-9.5 6.5S2.5 12 2.5 12z" />
			<circle cx="12" cy="12" r="3" />
		</>
	),
	'flame': (
		<>
			<path d="M12 3c1 3 4 4 4 8a4 4 0 0 1-8 0c0-2 1-3 1-3 0 2 1 3 2 3 0-3-1-5 1-8z" />
		</>
	),
	'globe': (
		<>
			<circle cx="12" cy="12" r="8.5" />
			<path d="M3.5 12h17" />
			<path d="M12 3.5c2.5 2.5 3.5 5.5 3.5 8.5s-1 6-3.5 8.5c-2.5-2.5-3.5-5.5-3.5-8.5s1-6 3.5-8.5z" />
		</>
	),
	'image': (
		<>
			<rect x="3.5" y="5" width="17" height="14" rx="2.5" />
			<circle cx="9" cy="10" r="1.6" />
			<path d="M4 17l5-5 4 4 3-3 4.5 4.5" />
		</>
	),
	'info': (
		<>
			<circle cx="12" cy="12" r="9" />
			<path d="M12 11v5.5M12 7.5v.5" />
		</>
	),
	'lock': (
		<>
			<rect x="5" y="11" width="14" height="9" rx="2" />
			<path d="M8 11V8a4 4 0 0 1 8 0v3" />
		</>
	),
	'logout': (
		<>
			<path d="M10 4.5H6.5a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2H10" />
			<path d="M14 8l4 4-4 4M18 12H9.5" />
		</>
	),
	'mail': (
		<>
			<rect x="3.5" y="5.5" width="17" height="13" rx="2.5" />
			<path d="M4.5 7.5l7.5 6 7.5-6" />
		</>
	),
	'memory': (
		<>
			<path d="M9 4a3 3 0 0 0-3 3 3 3 0 0 0-2 5 3 3 0 0 0 3 5 3 3 0 0 0 5 1V5a3 3 0 0 0-3-1zM15 4a3 3 0 0 1 3 3 3 3 0 0 1 2 5 3 3 0 0 1-3 5 3 3 0 0 1-5 1" />
		</>
	),
	'menu': (
		<>
			<path d="M4 12h16M4 8h16M4 16h16" />
		</>
	),
	'mic': (
		<>
			<rect x="9" y="3" width="6" height="11" rx="3" />
			<path d="M5 11a7 7 0 0 0 14 0M12 18v3" />
		</>
	),
	'minus': (
		<>
			<path d="M5 12h14" />
		</>
	),
	'more': (
		<>
			<g fill="currentColor" stroke="none">
			<circle cx="6" cy="12" r="1.6" />
			<circle cx="12" cy="12" r="1.6" />
			<circle cx="18" cy="12" r="1.6" />
			</g>
		</>
	),
	'plus': (
		<>
			<path d="M12 5v14M5 12h14" />
		</>
	),
	'progress-filled': (
		<>
			<path d="M5 15l4.5-4.5 3.5 3 6-6.5V19H5z" fill="currentColor" stroke="none" opacity=".22" />
			<path d="M4 19.5h16" />
			<path d="M5 15l4.5-4.5 3.5 3 6-6.5" />
			<circle cx="19" cy="7" r="1.6" fill="currentColor" stroke="none" />
		</>
	),
	'progress': (
		<>
			<path d="M4 19.5h16" />
			<path d="M5 15l4.5-4.5 3.5 3 6-6.5" />
			<circle cx="19" cy="7" r="1.6" fill="currentColor" stroke="none" />
		</>
	),
	'recipes-filled': (
		<>
			<path d="M3.5 11.5h17a8.5 8.5 0 0 1-17 0z" fill="currentColor" />
			<path d="M9 3.5c-1 1.2 1 2 0 3.5M13.5 3.5c-1 1.2 1 2 0 3.5" />
		</>
	),
	'recipes': (
		<>
			<path d="M3.5 11.5h17a8.5 8.5 0 0 1-17 0z" />
			<path d="M9 3.5c-1 1.2 1 2 0 3.5M13.5 3.5c-1 1.2 1 2 0 3.5" />
		</>
	),
	'retry': (
		<>
			<path d="M20 12a8 8 0 1 1-2.3-5.6M20 4v5h-5" />
		</>
	),
	'scale': (
		<>
			<rect x="4" y="4" width="16" height="16" rx="4" />
			<path d="M8.5 10.5a5 5 0 0 1 7 0" />
			<path d="M12 11l1.6-2" />
		</>
	),
	'search': (
		<>
			<circle cx="11" cy="11" r="6.5" />
			<path d="M16 16l4 4" />
		</>
	),
	'send': (
		<>
			<path d="M12 19V5M5 12l7-7 7 7" />
		</>
	),
	'settings': (
		<>
			<circle cx="12" cy="12" r="3" />
			<path d="M12 2v3M12 19v3M2 12h3M19 12h3M4.9 4.9l2.1 2.1M17 17l2.1 2.1M4.9 19.1L7 17M17 7l2.1-2.1" />
		</>
	),
	'share': (
		<>
			<path d="M12 15V4M8 8l4-4 4 4" />
			<path d="M6 11H5a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-8a1 1 0 0 0-1-1h-1" />
		</>
	),
	'sparkle': (
		<>
			<path d="M12 3l1.8 4.8L19 9.5l-4 3.4 1.2 5.1L12 15.4 7.8 18l1.2-5.1-4-3.4 5.2-1.7z" />
		</>
	),
	'stop': (
		<>
			<rect x="7" y="7" width="10" height="10" rx="2.5" fill="currentColor" stroke="none" />
		</>
	),
	'today': (
		<>
			<circle cx="12" cy="12" r="8" strokeWidth="3" opacity=".3" />
		</>
	),
	'trash': (
		<>
			<path d="M5 7h14M10 7V5h4v2M7 7l1 12h8l1-12" />
		</>
	),
	'trend-down': (
		<>
			<path d="M4 7l6 6 4-4 6 6" />
			<path d="M20 10v5h-5" />
		</>
	),
	'trend-flat': (
		<>
			<path d="M4 12h13" />
			<path d="M15 8.5l4 3.5-4 3.5" />
		</>
	),
	'walk': (
		<>
			<circle cx="13" cy="4.5" r="2" />
			<path d="M9 21l2-6 3 2v4M7 12l3-4h4l2 4 3 1" />
		</>
	),
}
